<?php 
/*
 *	Topspin Nav Menus
 *
 *	Usage: [topspin_store_nav_menu]
 *
 *	Available template variables
 *		storelist	(array)
 *
 *
 *	WARNING: DO NOT EDIT THIS FILE!
 *
 *	To edit the PHP, copy this file to your
 *	active theme's directory and edit from that
 *	new file.
 *
 *	Example: /wp-content/themes/<current-theme>/topspin-standard/nav-menu.php
 *
 */

if(!function_exists('topspin_navmenu_item')) {
	function topspin_navmenu_item($item) { ?>
		<li class="topspin-store-navmenu">
			<a class="topspin-store-navmenu" href="<?php echo get_permalink($item->ID); ?>"><?php echo $item->post_title; ?></a>
			<?php if(count($item->store_childs)) : ?>
				<ul class="topspin-store-navmenu"><?php foreach($item->store_childs as $child) : topspin_navmenu_item($child); endforeach; ?></ul>
			<?php endif; ?>
		</li>
	<?php }
} ?>

<div class="topspin-store-navmenu">
	<ul class="topspin-store-navmenu">
		<?php foreach($storelist as $item) : topspin_navmenu_item($item); endforeach; ?>
	</ul>
</div>

<script type="text/javascript">
$(function(){
   var path = '/' + location.pathname.substring(1);
   if ( path ) { 
     $('a[href$="' + path + '"]').attr('id','selected');
   }
});
</script>