<?php
/*
 *	WARNING: DO NOT EDIT THIS FILE!
 *
 *	To edit the PHP, copy this file to your
 *	active theme's directory and edit from that
 *	new file.
 *
 *	Example: /wp-content/themes/<current-theme>/topspin-simplified/featured-item.php
 *
 */
 ?>

<div class="topspin-featured-item">
    <div class="topspin-item-image"><img src="<?php echo $featureditem['default_image'];?>" /></div>
    <h2 class="topspin-item-title"><?php echo $featureditem['name'];?></h2>
    <div class="topspin-item-desc"><?php echo $featureditem['description'];?></div>
    <div class="topspin-item-price">Price: <?php echo $featureditem['symbol'];?><?php echo $featureditem['price'];?></div>
    <div class="topspin-item-buy"><a class="topspin-buy" href="<?php echo $featureditem['offer_url'];?>">Buy</a></div>
</div>
