<?php 
/*
 *	Topspin Nav Menus
 *
 *	Usage: [topspin_store_nav_menu]
 *
 *	Available template variables
 *		storelist	(array)
 *
 *
 *	WARNING: DO NOT EDIT THIS FILE!
 *
 *	To edit the PHP, copy this file to your
 *	active theme's directory and edit from that
 *	new file.
 *
 *	Example: /wp-content/themes/<current-theme>/topspin-simplified/nav-menu.php
 *
 */
?>

<div class="topspin-store-navmenu">
<ul class="topspin-store-navmenu">
<?php foreach ($storelist as $item) : ?>
  <li class="topspin-store-navmenu"><a class="topspin-store-navmenu" href="<?php bloginfo('wpurl'); ?>/<?php echo $item->post_name; ?>/"><?php echo $item->post_title; ?></a></li>
<?php endforeach; ?>
</ul>
</div>
<script type="text/javascript">
$(function(){
   var path = '/' + location.pathname.substring(1);
   if ( path ) { 
     $('a[href$="' + path + '"]').attr('id','selected');
   }
});
</script>