CREATE TABLE IF NOT EXISTS `<?php echo $wpdb->prefix;?>topspin_orders` (
  `id` int(11) NOT NULL,
  `artist_id` int(11) NOT NULL,
  `created_at` date NOT NULL,
  `subtotal` float NOT NULL,
  `tax` float NOT NULL,
  `currency` varchar(15) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `shipping_method_calculator` varchar(255) NOT NULL,
  `reshipment` varchar(255) NOT NULL,
  `fan` varchar(255) NOT NULL,
  `details_url` text NOT NULL,
  `exchange_rate` varchar(255) NOT NULL,
  `shipping_method_code` varchar(255) NOT NULL,
  `shipping_address_firstname` varchar(255) NOT NULL,
  `shipping_address_lastname` varchar(255) NOT NULL,
  `shipping_address_address1` varchar(255) NOT NULL,
  `shipping_address_address2` varchar(255) NOT NULL,
  `shipping_address_city` varchar(255) NOT NULL,
  `shipping_address_state` varchar(255) NOT NULL,
  `shipping_address_postal_code` varchar(255) NOT NULL,
  `shipping_address_country` varchar(255) NOT NULL,
  `shipping_address_phone` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `artist_id` (`artist_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;