CREATE TABLE IF NOT EXISTS `<?php echo $wpdb->prefix;?>topspin_orders_items` (
  `id` int(11) NOT NULL,
  `order_id` int(11) NOT NULL,
  `campaign_id` int(11) NOT NULL,
  `line_item_id` int(11) NOT NULL,
  `spin_name` varchar(255) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_type` varchar(255) NOT NULL,
  `merchandise_type` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `sku_id` int(11) NOT NULL,
  `sku_upc` varchar(255) NOT NULL,
  `sku_attributes` text NOT NULL,
  `factory_sku` varchar(255) NOT NULL,
  `shipped` tinyint(1) NOT NULL,
  `status` varchar(255) NOT NULL,
  `weight` text NOT NULL,
  `bundle_sku_id` int(11) NOT NULL,
  `shipping_date` date NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `order_id` (`order_id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `product_id` (`product_id`),
  KEY `bundle_sku_id` (`bundle_sku_id`),
  KEY `sku_id` (`sku_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
